// ============================================================
//  PROJETOS.JS — Arquivo de configuração de projetos XNT
//  ============================================================
//  Como adicionar um novo projeto:
//  1. Copie o bloco de exemplo no final do arquivo
//  2. Cole antes do ];
//  3. Preencha os campos
//  4. Salve e recarregue a página
// ============================================================

const PROJECTS = [

  // ──────────────────────────────────────────────────────────
  //  PROJETO: ATIVAÇÃO MIX MATHEUS — COCA-COLA CARNAVAL 2025
  // ──────────────────────────────────────────────────────────
  {
    slug: 'coca-cola-carnaval-2025',
    color: '#e61d2b',
    title: 'COCA-COLA CARNAVAL',
    subtitle: 'Ativação Mix Matheus • Carnaval 2025',
    year: '2025',
    category: 'DIREÇÃO DE ARTE',
    categorySlug: 'direcao-arte 3d design-grafico',
    role: 'DIREÇÃO DE ARTE',
    tags: ['Direção de Arte', '3D', 'Design Gráfico', 'Blender'],
    client: 'Coca-Cola Brasil',
    clientRole: 'Agência DVRGNT — Ativação Mix Matheus',
    heroImg: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/40075a231613777.688c3a9df30f1.png',
    intro: 'Em janeiro de 2025, participei deste projeto em colaboração com a equipe da Divergente, assinando a Direção de Arte, modelagem 3D e composição visual para a ativação de Carnaval da Coca-Cola no Mix Matheus.',
    body: 'A identidade visual criada seguiu fiel ao espírito vibrante do Carnaval, reforçando a presença da Coca-Cola com energia e impacto. O projeto foi essencial para testar ideias e traduzir conceitos 3D em equipe com ritmo e propósito.',
    extraBody: 'Cada peça foi pensada para reforçar a integração da marca à atmosfera do trio elétrico, com texturas, cores e modelagens que refletem a explosão visual do Carnaval pernambucano.',
    quote: 'A identidade visual seguiu fiel ao espírito vibrante do Carnaval, reforçando a presença da Coca-Cola com energia e impacto.',
    details: [
      { label: 'ANO',         value: '2025' },
      { label: 'FERRAMENTAS', value: 'Blender 3D, Photoshop' },
      { label: 'AGÊNCIA',     value: 'DVRGNT' },
      { label: 'ÁREA',        value: 'Direção de Arte + 3D' },
      { label: 'EVENTO',      value: 'Carnaval / Mix Matheus' },
      { label: 'CLIENTE',     value: 'Coca-Cola Brasil' },
    ],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/40075a231613777.688c3a9df30f1.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b9cb5c231613777.688c3a9df2783.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/3800a9231613777.688c3a9df1ba4.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/1f4863231613777.688c3e9cb8ca5.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/e1e73c231613777.688c3e9cb94a3.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/7d7ca0231613777.688c3e9cb851f.png',
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: STU 2023 — ESPORTES DA SORTE RECIFE
  // ──────────────────────────────────────────────────────────
  {
    slug: 'stu-2023',
    color: '#22c55e',
    title: 'STU 2023',
    subtitle: 'Skate Total Urbe • Esportes da Sorte',
    year: '2023',
    category: 'EDIÇÃO DE VÍDEO',
    categorySlug: 'video-editing direcao-arte',
    role: 'DIREÇÃO DE FOTOGRAFIA',
    tags: ['Edição de Vídeo', 'Fotografia', 'VFX', 'Recife'],
    client: 'Esportes da Sorte',
    clientRole: 'Agência DVRGNT — STU Skate Total Urbe 2023',
    heroImg: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/35602a220738855.67c8620ae5a84.png',
    intro: 'Tive o prazer de contribuir no STU Skate Total Urbe 2023 como Diretor de Fotografia pela agência DVRGNT, captando as ativações da Esportes da Sorte em Recife.',
    body: 'Junto ao time — Enrico (Fotografia e Ass. Captação de Vídeos) e Junior (Jive) — toda a cobertura foi editada e montada para apresentar com impacto a energia do evento e da marca patrocinadora.',
    extraBody: 'A direção de fotografia priorizou capturar o ritmo do evento e a identidade do skate de rua: enquadramentos baixos, contraste alto e movimento contínuo. O resultado: um material que respira a marca e o público.',
    quote: 'Capturar o STU foi traduzir velocidade, adrenalina e marca em um único frame.',
    details: [
      { label: 'ANO',         value: '2023' },
      { label: 'FERRAMENTAS', value: 'Premiere Pro, After Effects' },
      { label: 'AGÊNCIA',     value: 'DVRGNT' },
      { label: 'EVENTO',      value: 'STU Skate Total Urbe' },
      { label: 'FUNÇÃO',      value: 'Dir. Fotografia + Edição' },
      { label: 'CLIENTE',     value: 'Esportes da Sorte' },
    ],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/35602a220738855.67c8620ae5a84.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/312d53220738855.67c85fcf453ad.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/5e6308220738855.67c85fcf43bd4.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/626c3c220738855.67c85fcf45d72.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/687b0d220738855.67c85fcf46b96.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6b956b220738855.67c85fcf416cb.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/737ad8220738855.67c85fcf4645e.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/7434fb220738855.67c85fcf44ca1.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b3c513220738855.67c85fcf41ed4.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/e0f07c220738855.67c85fcf47fd2.jpg',
    ],
    media: [
      { type: 'video-slot', label: 'Aftermovie em produção', format: 'WEBM · DESTAQUE' },
      { type: 'image-full', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/312d53220738855.67c85fcf453ad.jpg' },
      { type: 'image-pair',
        left:  'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/5e6308220738855.67c85fcf43bd4.jpg',
        right: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/626c3c220738855.67c85fcf45d72.jpg' },
      { type: 'image-grid', cols: 3, images: [
        'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/687b0d220738855.67c85fcf46b96.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6b956b220738855.67c85fcf416cb.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/737ad8220738855.67c85fcf4645e.jpg',
      ]},
      { type: 'image-pair',
        left:  'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/7434fb220738855.67c85fcf44ca1.jpg',
        right: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b3c513220738855.67c85fcf41ed4.jpg' },
      { type: 'image-full', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/e0f07c220738855.67c85fcf47fd2.jpg' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: KALERA
  // ──────────────────────────────────────────────────────────
  {
    slug: 'kalera',
    color: '#ec4899',
    title: 'KALERA',
    subtitle: 'Thumbnails & Identidade Visual • FURIA',
    year: '2022',
    category: 'DESIGN GRÁFICO',
    categorySlug: 'design-grafico',
    role: 'DESIGN GRÁFICO',
    tags: ['Design Gráfico', 'Thumbnails', 'Social Media', 'FURIA'],
    client: 'Kalera / FURIA',
    clientRole: 'Streamer & Criadora de conteúdo — FURIA',
    heroImg: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/57c16f145289651.629b959114636.png',
    intro: 'Camila Viera "Kalera" é cantora, dubladora, desenhista e streamer da FURIA, ligada a causas LGBTQIA+. O projeto focou em redesenhar as thumbnails do canal com identidade visual atualizada e direcionada ao público.',
    body: 'Antes, as thumbnails da Kalera eram feitas de modo aleatório e não usavam fotos atuais do rosto dela. A proposta foi entregar peças mais direcionadas, com a presença da streamer em destaque e linguagem visual coerente com o público do canal.',
    extraBody: 'Em parceria com o designer Lucas Fonseca, desenvolvemos briefings específicos para cada peça, criando uma identidade mais coesa e chamativa. Hoje faz mais de um ano que trabalho com a Kalera — e muitos desses trabalhos seguem ativos no canal dela no YouTube.',
    quote: 'Thumbnails são a primeira impressão — precisavam contar a história antes do clique.',
    details: [
      { label: 'ANO',         value: '2022' },
      { label: 'FERRAMENTAS', value: 'Photoshop, Illustrator' },
      { label: 'ÁREA',        value: 'Design Gráfico / Social Media' },
      { label: 'TIPO',        value: 'Thumbnails + Identidade Visual' },
      { label: 'PARCERIA',    value: 'Lucas Fonseca (Design)' },
      { label: 'CLIENTE',     value: 'Kalera / FURIA' },
    ],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200_webp/57c16f145289651.629b959114636.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/fs/05fcfe145289651.629b95906c44a.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/fs/ab0a8f145289651.629b95906bb86.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/fs/48341a145289651.629b9590b430c.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/fs/c1d06b145289651.629b9590b4853.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/fs/cca29b145289651.629b95906cbc8.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/da14bb145289651.629ba155ca91c.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/hd_webp/6638e6145289651.629ba290e72e8.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/source/5b07fa145289651.629b959114c8d.gif',
      'https://mir-s3-cdn-cf.behance.net/project_modules/source/744883145289651.629ba1fc731c4.gif',
    ],
    // Layout customizado (sobrescreve o render padrão de galeria)
    media: [
      { type: 'gif-divider', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/source/5b07fa145289651.629b959114c8d.gif' },
      { type: 'section-title', value: 'ANTES' },
      { type: 'text', body: 'Antes, as thumbnails da Kalera eram feitas de modo aleatório e não usavam fotos atuais do rosto dela. A proposta foi entregar peças mais direcionadas, com a presença da streamer em destaque e linguagem visual coerente com o público do canal.' },
      { type: 'image-grid', cols: 2, images: [
        'https://mir-s3-cdn-cf.behance.net/project_modules/fs/05fcfe145289651.629b95906c44a.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/fs/ab0a8f145289651.629b95906bb86.jpg',
      ]},
      { type: 'section-title', value: 'DEPOIS' },
      { type: 'image-grid', cols: 2, images: [
        'https://mir-s3-cdn-cf.behance.net/project_modules/fs/48341a145289651.629b9590b430c.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/fs/c1d06b145289651.629b9590b4853.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/fs/cca29b145289651.629b95906cbc8.jpg',
        'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/da14bb145289651.629ba155ca91c.jpg',
      ]},
      { type: 'video-slot', label: 'Reel em produção', format: 'WEBM · 01' },
      { type: 'gif-divider', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/source/744883145289651.629ba1fc731c4.gif' },
      { type: 'text', body: 'Hoje faz mais de um ano que trabalho com a Kalera — e muitos desses trabalhos seguem ativos no canal dela no YouTube. Em parceria com o designer Lucas Fonseca, desenvolvemos briefings específicos para cada peça, criando uma identidade mais coesa e chamativa.' },
      { type: 'video-slot', label: 'Highlight do canal', format: 'WEBM · 02' },
      { type: 'image-full',
        src: 'https://mir-s3-cdn-cf.behance.net/project_modules/hd_webp/6638e6145289651.629ba290e72e8.png',
        caption: 'Canal da Kalera no YouTube' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: GAMEPLAN | VIDEO TRAILER
  // ──────────────────────────────────────────────────────────
  {
    slug: 'gameplan',
    color: '#06b6d4',
    title: 'GAMEPLAN',
    subtitle: 'Trailer institucional • Gametech',
    year: '2022',
    category: 'EDIÇÃO DE VÍDEO',
    categorySlug: 'video-editing motion-design',
    role: 'VIDEO EDITING',
    tags: ['Edição de Vídeo', 'Motion Design', 'Trailer', 'GameTech'],
    client: 'GamePlan',
    clientRole: 'Gametech — mercado de jogos',
    heroImg: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/de626e144297699.628a453bd9b1a.png',
    intro: 'A GamePlan é uma gametech criada em 2014 que fornece desenvolvimento e tecnologia para empresas no mercado de jogos, com soluções de co-desenvolvimento, tecnologia, dados e inteligência.',
    body: 'O trailer foi desenvolvido para apresentar a plataforma de forma dinâmica e impactante, traduzindo em linguagem audiovisual a proposta de inovação e tecnologia da GamePlan para o setor de games.',
    quote: 'Traduzir tecnologia em narrativa audiovisual é o desafio mais estimulante.',
    details: [
      { label: 'ANO',         value: '2022' },
      { label: 'FERRAMENTAS', value: 'Premiere Pro, After Effects' },
      { label: 'TIPO',        value: 'Video Trailer' },
      { label: 'ÁREA',        value: 'Edição + Motion Design' },
      { label: 'FORMATO',     value: 'Digital / YouTube' },
      { label: 'CLIENTE',     value: 'GamePlan' },
    ],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/de626e144297699.628a453bd9b1a.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/495557144297699.628a42ed34ec2.png',
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: FLYING HIGH — 3D
  // ──────────────────────────────────────────────────────────
  {
    slug: 'flying-high',
    color: '#f97316',
    title: 'FLYING HIGH',
    subtitle: 'Visualização 3D • Streetwear',
    year: '2021',
    category: 'MODELAGEM 3D',
    categorySlug: '3d',
    role: '3D',
    tags: ['3D', 'Streetwear', 'Product Visualization', 'Blender'],
    client: 'Urban Joy',
    clientRole: 'Loja de streetwear — projeto pessoal',
    instagram: 'https://www.instagram.com/xntvisuals/',
    heroImg: 'https://mir-s3-cdn-cf.behance.net/project_modules/disp/5dc3d0123129763.60e7d928cebdc.png',
    intro: 'Projeto pessoal de modelagem e visualização 3D desenvolvido para a Urban Joy, loja brasileira do segmento streetwear.',
    body: 'Cada cena foi construída com atenção a iluminação, texturas e composição para entregar visuais com presença de mundo real. A proposta era criar renders que traduzissem a identidade streetwear da marca em composições tridimensionais impactantes.',
    extraBody: 'Foi um trabalho que cruzou universos: moda, fotografia, estilo urbano e 3D. As ferramentas envolvidas foram Blender, Marvelous Designer, Cinema 4D, After Effects e Photoshop — cada uma puxando uma camada da composição final.',
    quote: 'O 3D precisava ter textura, peso e a atitude do streetwear.',
    details: [
      { label: 'ANO',         value: '2021' },
      { label: 'FERRAMENTAS', value: 'Blender, Marvelous, C4D' },
      { label: 'TIPO',        value: 'Product Visualization' },
      { label: 'ENTREGA',     value: 'Stills + GIF animado' },
      { label: 'SEGMENTO',    value: 'Streetwear' },
      { label: 'CLIENTE',     value: 'Urban Joy' },
    ],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/disp/5dc3d0123129763.60e7d928cebdc.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/disp/383e44123129763.60e7d928ce0ba.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/disp/b74210123129763.60e7d928ce68f.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/source/a7ce24123129763.610024850ba33.gif',
    ],
    media: [
      { type: 'image-full', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/disp/5dc3d0123129763.60e7d928cebdc.png' },
      { type: 'video-slot', label: 'Render reel em produção', format: 'WEBM · DESTAQUE' },
      { type: 'image-pair',
        left:  'https://mir-s3-cdn-cf.behance.net/project_modules/disp/383e44123129763.60e7d928ce0ba.png',
        right: 'https://mir-s3-cdn-cf.behance.net/project_modules/disp/b74210123129763.60e7d928ce68f.png' },
      { type: 'gif-divider', src: 'https://mir-s3-cdn-cf.behance.net/project_modules/source/a7ce24123129763.610024850ba33.gif' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: CAMPANHA OFICIAL DO NÁUTICO
  // ──────────────────────────────────────────────────────────
  {
    slug: 'nauticope',
    color: '#94a3b8',
    title: 'CAMPANHA OFICIAL DO NÁUTICO',
    subtitle: 'Nova camisa branca • Streetwear',
    year: '2025',
    category: 'DIREÇÃO DE ARTE',
    categorySlug: 'direcao-arte video-editing motion-design',
    role: 'DIREÇÃO / EDIÇÃO',
    tags: ['Direção de Arte', 'Edição de Vídeo', 'Campanha', 'Streetwear'],
    client: 'Nauticope',
    clientRole: 'Marca de streetwear — campanha do produto',
    instagram: 'https://www.instagram.com/nauticope/',
    heroImg: 'img/nauticope/frame-25.jpg',
    intro: 'Campanha oficial da Nauticope para o lançamento da nova camisa branca — direção e edição do vídeo principal: "A gente sonhou, criou, viveu. Agora é a vez do mundo sentir."',
    body: 'O projeto reuniu produção executiva (@gmaiaphotos), direção (@rcdan) e edição em ritmo de campanha de moda streetwear, com peso, atmosfera e identidade visual coesa em cada frame.',
    extraBody: 'A montagem foi pensada para conectar o produto ao universo da marca — cada cena traduz movimento, vestibilidade e a estética crua do streetwear urbano.',
    quote: 'A gente sonhou, criou, viveu. Agora é a vez do mundo sentir.',
    details: [
      { label: 'ANO',         value: '2025' },
      { label: 'FERRAMENTAS', value: 'DaVinci Resolve, After Effects' },
      { label: 'PRODUÇÃO',    value: '@gmaiaphotos' },
      { label: 'DIREÇÃO',     value: '@rcdan' },
      { label: 'TIPO',        value: 'Campanha de Produto' },
      { label: 'CLIENTE',     value: 'Nauticope' },
    ],
    gallery: [
      'img/nauticope/frame-25.jpg',
      'img/nauticope/frame-03.jpg',
      'img/nauticope/frame-10.jpg',
      'img/nauticope/frame-18.jpg',
      'img/nauticope/frame-32.jpg',
      'img/nauticope/frame-40.jpg',
    ],
    media: [
      { type: 'video-slot',
        src: 'WEBM/Campanha%20oficial%20do%20nauticope.%20A%20gente%20sonhou%2C%20criou%2C%20viveu.%20Agora%20%C3%A9%20a%20vez%20do%20mundo%20sentir-.webm',
        fallback: 'Campanha oficial do nauticope. A gente sonhou, criou, viveu. Agora é a vez do mundo sentir..mp4',
        label: 'Campanha oficial',
        format: 'MP4 · DESTAQUE',
        autoplay: false },
      { type: 'image-full', src: 'img/nauticope/frame-03.jpg' },
      { type: 'image-pair',
        left:  'img/nauticope/frame-10.jpg',
        right: 'img/nauticope/frame-18.jpg' },
      { type: 'image-full', src: 'img/nauticope/frame-32.jpg' },
      { type: 'image-full', src: 'img/nauticope/frame-40.jpg' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: WISE
  // ──────────────────────────────────────────────────────────
  {
    slug: 'wise',
    color: '#dc2626',
    title: 'WISE',
    subtitle: 'Direção & edição • Conteúdo',
    year: '2025',
    category: 'EDIÇÃO DE VÍDEO',
    categorySlug: 'video-editing direcao-arte',
    role: 'DIREÇÃO / EDIÇÃO',
    tags: ['Edição de Vídeo', 'Direção de Arte', 'Conteúdo', 'Streetwear'],
    client: 'WISE',
    clientRole: 'Conteúdo audiovisual',
    heroImg: 'img/wise/frame-18.jpg',
    intro: 'Projeto WISE — conteúdo audiovisual com direção e edição, traduzindo a vivência e a atmosfera de espaços criativos em uma narrativa visual coesa.',
    body: 'A montagem foi pensada para conectar estética, ambiente e identidade — cada frame respira a vibração do espaço e da marca, com ritmo e composição alinhados ao universo streetwear.',
    extraBody: 'Cada cena foi escolhida para construir uma sequência impactante e fluída, mantendo o peso visual do material bruto e a presença da marca.',
    quote: 'Visualizar é sentir antes de explicar.',
    details: [
      { label: 'ANO',         value: '2025' },
      { label: 'FERRAMENTAS', value: 'DaVinci Resolve, After Effects' },
      { label: 'TIPO',        value: 'Conteúdo audiovisual' },
      { label: 'FUNÇÃO',      value: 'Direção + Edição' },
      { label: 'FORMATO',     value: 'Reels / Digital' },
      { label: 'CLIENTE',     value: 'WISE' },
    ],
    gallery: [
      'img/wise/frame-18.jpg',
      'img/wise/frame-04.jpg',
      'img/wise/frame-11.jpg',
      'img/wise/frame-25.jpg',
      'img/wise/frame-32.jpg',
      'img/wise/frame-39.jpg',
      'img/wise/frame-46.jpg',
      'img/wise/frame-54.jpg',
    ],
    media: [
      { type: 'video-slot',
        src: 'WEBM/WISE_1.webm',
        fallback: 'WISE.mp4',
        label: 'WISE',
        format: 'MP4 · DESTAQUE',
        autoplay: false },
      { type: 'image-full', src: 'img/wise/frame-02.jpg' },
      { type: 'image-pair',
        left:  'img/wise/frame-06.jpg',
        right: 'img/wise/frame-16.jpg' },
      { type: 'image-full', src: 'img/wise/frame-21.jpg' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: VIDA CARA DELUXE — OROCHI
  // ──────────────────────────────────────────────────────────
  {
    slug: 'vida-cara-deluxe',
    color: '#facc15',
    title: 'VIDA CARA DELUXE',
    subtitle: 'Album Art 3D • Orochi',
    year: '2023',
    category: 'MODELAGEM 3D',
    categorySlug: '3d',
    role: '3D',
    tags: ['3D', 'Blender', 'Album Art', 'Orochi'],
    client: 'Orochi',
    clientRole: 'Colaboração criativa — arte do álbum',
    instagram: 'https://www.instagram.com/orochi/',
    heroImg: 'img/vida-cara/cover.jpg',
    intro: 'Participação na arte do álbum "Vida Cara Deluxe" do Orochi, desenvolvendo o modelo 3D em colaboração com @chestte.r e @ferbersa.art.',
    body: 'Cada detalhe do modelo foi construído com atenção ao universo visual do projeto. Um trabalho que marcou uma etapa importante da trajetória em 3D, junto a artistas que estão em outro nível.',
    quote: 'Toda vez que olho vem aquele conforto de que o tempo investido em mim tá rendendo.',
    details: [
      { label: 'ANO',         value: '2023' },
      { label: 'FERRAMENTAS', value: 'Blender 3D' },
      { label: 'TIPO',        value: 'Album Art / 3D' },
      { label: 'COLABS',      value: '@chestte.r, @ferbersa.art' },
      { label: 'ENTREGA',     value: 'Stills' },
      { label: 'CLIENTE',     value: 'Orochi' },
    ],
    gallery: [
      'img/vida-cara/cover.jpg',
      'img/vida-cara/gallery-1.jpg',
      'img/vida-cara/gallery-2.jpg',
      'img/vida-cara/gallery-3.jpg',
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: CASA DA BARRA — CARLINHOS MAIA
  // ──────────────────────────────────────────────────────────
  {
    slug: 'casa-da-barra',
    color: '#0ea5e9',
    title: 'CASA DA BARRA',
    subtitle: 'Captação & Edição • Carlinhos Maia',
    year: '2024',
    category: 'EDIÇÃO DE VÍDEO',
    categorySlug: 'video-editing direcao-arte',
    role: 'CAPTAÇÃO / EDIÇÃO',
    tags: ['Edição de Vídeo', '3D', 'Captação', 'Blender'],
    client: 'Carlinhos Maia',
    clientRole: 'Agência Divergente — captação e edição',
    instagram: 'https://www.instagram.com/reel/C4yDdPPM79d/',
    verticalMedia: true,
    heroImg: 'img/casa-da-barra/frame-44.jpg',
    intro: 'Captação completa do projeto da Casa da Barra do Carlinhos Maia — desde a plotagem/adesivação do caminhão e sua saída de Recife levando os prêmios, até a chegada em São Miguel dos Milagres (AL), onde acompanhei e registrei a montagem e produção das ativações.',
    body: 'O projeto foi desenvolvido pela Agência Divergente. Eu acompanhei toda a logística e produção — o trajeto do caminhão, a chegada na Casa da Barra e o passo a passo da montagem das ativações no local. A Terra 3D foi modelada no Blender e a edição final passou pelo DaVinci Resolve.',
    extraBody: 'A cobertura contou também com filmagens do @lucasg.editor para complementar o registro do espaço. Foi um projeto que juntou produção audiovisual, logística de campo e 3D num único entregável.',
    quote: 'Quão longe já fui — o tanto de gente que viu meu trabalho e curtiu.',
    details: [
      { label: 'ANO',         value: '2024' },
      { label: 'FERRAMENTAS', value: 'Blender, DaVinci Resolve' },
      { label: 'AGÊNCIA',     value: 'Divergente' },
      { label: 'FUNÇÃO',      value: 'Captação + Edição + 3D' },
      { label: 'LOCAL',       value: 'São Miguel dos Milagres, AL' },
      { label: 'CLIENTE',     value: 'Carlinhos Maia' },
    ],
    gallery: [
      'img/casa-da-barra/frame-44.jpg',
      'img/casa-da-barra/frame-04.jpg',
      'img/casa-da-barra/frame-14.jpg',
      'img/casa-da-barra/frame-24.jpg',
      'img/casa-da-barra/frame-34.jpg',
      'img/casa-da-barra/frame-54.jpg',
      'img/casa-da-barra/frame-64.jpg',
      'img/casa-da-barra/frame-74.jpg',
    ],
    media: [
      { type: 'video-slot',
        src: 'Casa%20da%20barra%20-%20Carlinhos%20Maia.mp4',
        label: 'Casa da Barra — Edição final',
        format: 'MP4 · DESTAQUE',
        autoplay: false },
      { type: 'section-title', value: 'PLOTAGEM E SAÍDA DO CAMINHÃO' },
      { type: 'image-pair',
        left:  'img/casa-da-barra/frame-04.jpg',
        right: 'img/casa-da-barra/frame-14.jpg' },
      { type: 'image-full', src: 'img/casa-da-barra/frame-24.jpg' },
      { type: 'section-title', value: 'CHEGADA E MONTAGEM EM SÃO MIGUEL' },
      { type: 'image-grid', cols: 3, images: [
        'img/casa-da-barra/frame-34.jpg',
        'img/casa-da-barra/frame-54.jpg',
        'img/casa-da-barra/frame-64.jpg',
      ]},
      { type: 'image-full', src: 'img/casa-da-barra/frame-74.jpg' },
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: BY NEVOA — 3D FASHION
  // ──────────────────────────────────────────────────────────
  {
    slug: 'by-nevoa',
    color: '#a3886e',
    title: 'BY NEVOA',
    subtitle: '3D Fashion • Festival Noar',
    year: '2025',
    category: 'MODELAGEM 3D',
    categorySlug: '3d design-grafico',
    role: '3D / DESIGN GRÁFICO',
    tags: ['3D', 'Fashion', 'Blender', 'Product Design'],
    client: 'By Nevoa',
    clientRole: 'Coleção cápsula — Festival Noar',
    instagram: 'https://www.instagram.com/reel/DR7MWFSDYUY/',
    heroImg: 'img/by-nevoa/cover.jpg',
    intro: 'Colaboração com a By Nevoa para a Feira das Feiras — uma coleção cápsula de bonés customizados exclusivos para o Festival Noar, em parceria com a Futuro Black.',
    body: 'Os bonés foram visualizados em 3D, traduzindo a identidade da marca em peças únicas para o evento. Um projeto que une moda, cultura e modelagem digital.',
    quote: 'Moda, cultura e 3D se encontrando num único projeto — é exatamente nisso que acredito.',
    details: [
      { label: 'ANO',         value: '2025' },
      { label: 'FERRAMENTAS', value: 'Blender 3D' },
      { label: 'TIPO',        value: '3D Fashion / Product Design' },
      { label: 'EVENTO',      value: 'Festival Noar' },
      { label: 'PARCERIA',    value: 'Futuro Black' },
      { label: 'CLIENTE',     value: 'By Nevoa' },
    ],
    gallery: [
      'img/by-nevoa/cover.jpg',
      'img/by-nevoa/gallery-1.jpg',
      'img/by-nevoa/gallery-2.jpg',
    ],
    video: null,
  },

  // ──────────────────────────────────────────────────────────
  //  PROJETO: BIENAL PE — DIREÇÃO DE ANIMAÇÃO
  // ──────────────────────────────────────────────────────────
  {
    slug: 'bienal-pe',
    color: '#3b82f6',
    title: 'BIENAL PE',
    subtitle: 'Direção de animação • Globo PE / SBT',
    year: '2025',
    category: 'MOTION DESIGN',
    categorySlug: 'motion-design direcao-arte',
    role: 'DIREÇÃO DE ANIMAÇÃO',
    tags: ['Motion Design', 'Animação', 'Direção de Arte', 'TV'],
    client: 'XV Bienal Internacional do Livro de PE',
    clientRole: 'Agência Amarelo — veiculação Globo PE / TV Jornal SBT',
    heroImg: 'img/bienal-pe/frame-11.jpg',
    intro: 'Direção de animação do comercial da XV Bienal Internacional do Livro de Pernambuco, em colaboração com a Agência Amarelo. Veiculado na Globo Pernambuco e TV Jornal SBT.',
    body: 'Um projeto que exigiu entrar em terrenos novos: registro na ANCINE, CRT, formatos de TV e direção de narração. A narração ficou com @chocoresco_, que deu mais vida à obra. Apesar dos desafios pessoais do período, é um trabalho que carrega história e orgulho.',
    quote: 'Se você vir esse projeto animado na sua TV — eu fiz parte disso.',
    details: [
      { label: 'ANO',         value: '2025' },
      { label: 'FERRAMENTAS', value: 'After Effects, Blender' },
      { label: 'AGÊNCIA',     value: 'Agência Amarelo' },
      { label: 'VEICULAÇÃO',  value: 'Globo PE + TV Jornal SBT' },
      { label: 'FUNÇÃO',      value: 'Direção de Animação' },
      { label: 'CLIENTE',     value: 'Bienal Internacional do Livro PE' },
    ],
    gallery: [
      'img/bienal-pe/frame-11.jpg',
      'img/bienal-pe/frame-02.jpg',
      'img/bienal-pe/frame-06.jpg',
      'img/bienal-pe/frame-16.jpg',
      'img/bienal-pe/frame-21.jpg',
      'img/bienal-pe/frame-25.jpg',
    ],
    media: [
      { type: 'video-slot',
        src: 'WEBM/BIENAL%20PE%20-%20DIRE%C3%87%C3%83O%20DE%20ANIMA%C3%87%C3%83O_1.webm',
        fallback: 'BIENAL%20PE%20-%20DIRE%C3%87%C3%83O%20DE%20ANIMA%C3%87%C3%83O.mp4',
        label: 'Bienal PE — Animação principal',
        format: 'MP4 · DESTAQUE',
        autoplay: false },
      { type: 'image-pair',
        left:  'img/bienal-pe/frame-02.jpg',
        right: 'img/bienal-pe/frame-06.jpg' },
      { type: 'image-full', src: 'img/bienal-pe/frame-16.jpg' },
      { type: 'image-pair',
        left:  'img/bienal-pe/frame-21.jpg',
        right: 'img/bienal-pe/frame-25.jpg' },
      { type: 'video-slot',
        src: 'WEBM/BIENAL%20PE%20-%20DIRE%C3%87%C3%83O%20DE%20ANIMA%C3%87%C3%83O%202_1.webm',
        fallback: 'BIENAL%20PE%20-%20DIRE%C3%87%C3%83O%20DE%20ANIMA%C3%87%C3%83O%202.mp4',
        label: 'Bienal PE — Variação curta',
        format: 'MP4 · 02',
        autoplay: false },
    ],
    instagram: 'https://www.instagram.com/p/DOly-gJlWVg/',
    video: null,
  },

  // ══════════════════════════════════════════════════════════
  //  ► ADICIONE NOVOS PROJETOS AQUI ◄
  //  Copie o bloco abaixo, remova os comentários e preencha:
  // ══════════════════════════════════════════════════════════

  // {
  //   slug: 'meu-novo-projeto',
  //   title: 'NOME DO PROJETO',
  //   subtitle: 'Descrição curta • Cliente',
  //   year: '2025',
  //   category: 'MOTION DESIGN',
  //   categorySlug: 'motion-design',
  //   role: 'MOTION DESIGN',
  //   tags: ['Tag 1', 'Tag 2'],
  //   client: 'Nome do Cliente',
  //   clientRole: 'Tipo de parceria',
  //   heroImg: 'URL_DA_IMAGEM_PRINCIPAL',
  //   intro: 'Primeiro parágrafo descritivo.',
  //   body: 'Segundo parágrafo com detalhes do processo.',
  //   extraBody: 'Parágrafo opcional adicional.',
  //   quote: 'Uma frase que resume o projeto.',
  //   details: [
  //     { label: 'ANO',         value: '2025' },
  //     { label: 'FERRAMENTAS', value: 'After Effects' },
  //     { label: 'FORMATO',     value: 'Reels' },
  //     { label: 'CLIENTE',     value: 'Nome do Cliente' },
  //   ],
  //   gallery: [
  //     'URL_IMAGEM_1',
  //     'URL_IMAGEM_2',
  //   ],
  //   video: null,
  // },

];
